Controllers/HorsesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace SkachkiWebApp.Controllers
{
    public class HorsesController : Controller
    {
        private readonly ApplicationContext _context;

        public HorsesController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Horses
        public async Task<IActionResult> Index()
        {
            var applicationContext = _context.Horses.Include(h => h.HorseOwner);
            return View(await applicationContext.ToListAsync());
        }

        // GET: Horses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Horses == null)
            {
                return NotFound();
            }

            var horseModel = await _context.Horses
                .Include(h => h.HorseOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (horseModel == null)
            {
                return NotFound();
            }

            return View(horseModel);
        }

        // GET: Horses/Create
        public IActionResult Create()
        {
            ViewBag.HorseOwners = new SelectList(_context.HorseOwners, "Id", "Name");
            ViewBag.Sex = new SelectList(new string[] { "Male", "Female" });
            return View();
        }

        // POST: Horses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nickname,Sex,DOB,HorseOwnerId")] HorseModel horseModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(horseModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorseOwnerId"] = new SelectList(_context.HorseOwners, "Id", "Name", horseModel.HorseOwnerId);
            return View(horseModel);
        }

        // GET: Horses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Horses == null)
            {
                return NotFound();
            }

            var horseModel = await _context.Horses.FindAsync(id);
            if (horseModel == null)
            {
                return NotFound();
            }
            ViewBag.HorseOwners = new SelectList(_context.HorseOwners, "Id", "Name", horseModel.HorseOwnerId);
            ViewBag.Sex = new SelectList(new string[] { "Male", "Female" });
            return View(horseModel);
        }

        // POST: Horses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nickname,Sex,DOB,HorseOwnerId")] HorseModel horseModel)
        {
            if (id != horseModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(horseModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HorseModelExists(horseModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorseOwnerId"] = new SelectList(_context.HorseOwners, "Id", "Id", horseModel.HorseOwnerId);
            return View(horseModel);
        }

        // GET: Horses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Horses == null)
            {
                return NotFound();
            }

            var horseModel = await _context.Horses
                .Include(h => h.HorseOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (horseModel == null)
            {
                return NotFound();
            }

            return View(horseModel);
        }

        // POST: Horses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Horses == null)
            {
                return Problem("Entity set 'ApplicationContext.Horses'  is null.");
            }
            var horseModel = await _context.Horses.FindAsync(id);
            if (horseModel != null)
            {
                _context.Horses.Remove(horseModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HorseModelExists(int id)
        {
          return (_context.Horses?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/IppodromsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace SkachkiWebApp.Controllers
{
    public class IppodromsController : Controller
    {
        private ApplicationContext _context;
        public IppodromsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Ippodroms
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ippodroms.ToListAsync());
        }

        // GET: Ippodroms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ippodroms == null)
            {
                return NotFound();
            }

            var ippodrom = await _context.Ippodroms.FirstOrDefaultAsync(m => m.Id == id);
            if (ippodrom == null)
            {
                return NotFound();
            }

            return View(ippodrom);
        }

        // GET: Ippodroms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ippodroms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Address,Description")] IppodromModel ippodrom)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ippodrom);
                _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ippodrom);
        }

        // GET: Ippodroms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ippodroms == null)
            {
                return NotFound();
            }

            var ippodrom = await _context.Ippodroms.FindAsync(id);
            if (ippodrom == null)
            {
                return NotFound();
            }
            return View(ippodrom);
        }

        // POST: Ippodroms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Address,Description")] IppodromModel ippodrom)
        {
            if (id != ippodrom.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ippodrom);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IppodromExists(ippodrom.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ippodrom);
        }

        // GET: Ippodroms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ippodroms == null)
            {
                return NotFound();
            }

            var ippodrom = await _context.Ippodroms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ippodrom == null)
            {
                return NotFound();
            }

            return View(ippodrom);
        }

        // POST: Ippodroms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ippodroms == null)
            {
                return Problem("Entity set 'ApplicationContext.Ippodroms'  is null.");
            }
            var ippodrom = await _context.Ippodroms.FindAsync(id);
            if (ippodrom != null)
            {
                _context.Ippodroms.Remove(ippodrom);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }
        
        // Test if Ippodrom DB line exists
        private bool IppodromExists(int id)
        {
            return (_context.Ippodroms?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/JokeysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace SkachkiWebApp.Controllers
{
    public class JokeysController : Controller
    {
        private readonly ApplicationContext _context;

        public JokeysController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Jokeys
        public async Task<IActionResult> Index()
        {
              return _context.Jokeys != null ? 
                          View(await _context.Jokeys.ToListAsync()) :
                          Problem("Entity set 'ApplicationContext.Jokeys'  is null.");
        }

        // GET: Jokeys/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jokeys == null)
            {
                return NotFound();
            }

            var jokey = await _context.Jokeys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jokey == null)
            {
                return NotFound();
            }

            return View(jokey);
        }

        // GET: Jokeys/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jokeys/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DOB,Rating")] JokeyModel jokey)
        {
            if (ModelState.IsValid)
            {
                if (jokey.Rating == null) jokey.Rating = 0;
                _context.Add(jokey);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jokey);
        }

        // GET: Jokeys/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jokeys == null)
            {
                return NotFound();
            }

            var jokey = await _context.Jokeys.FindAsync(id);
            if (jokey == null)
            {
                return NotFound();
            }
            return View(jokey);
        }

        // POST: Jokeys/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DOB,Rating")] JokeyModel jokey)
        {
            if (id != jokey.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jokey);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokeyExists(jokey.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jokey);
        }

        // GET: Jokeys/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Jokeys == null)
            {
                return NotFound();
            }

            var jokey = await _context.Jokeys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jokey == null)
            {
                return NotFound();
            }

            return View(jokey);
        }

        // POST: Jokeys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Jokeys == null)
            {
                return Problem("Entity set 'ApplicationContext.Jokeys'  is null.");
            }
            var jokey = await _context.Jokeys.FindAsync(id);
            if (jokey != null)
            {
                _context.Jokeys.Remove(jokey);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokeyExists(int id)
        {
          return (_context.Jokeys?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Areas/admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RoyaltyHorse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SkachkiWebApp.styles.css" asp-append-version="true" />

    <style>
        .img-thumbnail{
            max-width: 300px;
            max-height: auto;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RoyaltyHorse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="profile" asp-controller="Home" asp-action="Index">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Домашняя страница</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Ippodroms" asp-action="Index">Ипподромы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Competitions" asp-action="Index">Соревнования</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="CompetitionTickets" asp-action="Index">Участие в соревнованиях</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Jokeys" asp-action="Index">Жокеи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="Horses" asp-action="Index">Лошади</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="admin" asp-controller="HorseOwners" asp-action="Index">Владельцы лошадей</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RoyaltyHorse - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>