Controllers/CompetitionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace SkachkiWebApp.Controllers
{
    public class CompetitionsController : Controller
    {
        private readonly ApplicationContext _context;

        public CompetitionsController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Competitions
        public async Task<IActionResult> Index()
        {
            var applicationContext = _context.Competitions.Include(c => c.Ippodrom);
            return View(await applicationContext.ToListAsync());
        }

        // GET: Competitions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Competitions == null)
            {
                return NotFound();
            }

            var competition = await _context.Competitions
                .Include(c => c.Ippodrom)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (competition == null)
            {
                return NotFound();
            }

            return View(competition);
        }

        // GET: Competitions/Create
        public IActionResult Create()
        {
            ViewBag.Ippodroms = new SelectList(_context.Ippodroms, "Id", "Address");
            return View();
        }

        // POST: Competitions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Date,IppodromId")] CompetitionModel competition)
        {
            if (ModelState.IsValid)
            {
                _context.Add(competition);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IppodromId"] = new SelectList(_context.Ippodroms, "Id", "Address", competition.IppodromId);
            return View(competition);
        }

        // GET: Competitions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Competitions == null)
            {
                return NotFound();
            }

            var competition = await _context.Competitions.FindAsync(id);
            if (competition == null)
            {
                return NotFound();
            }
            ViewBag.Ippodroms = new SelectList(_context.Ippodroms, "Id", "Address", competition.IppodromId);
            return View(competition);
        }

        // POST: Competitions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Date,IppodromId")] CompetitionModel competition)
        {
            if (id != competition.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(competition);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompetitionExists(competition.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IppodromId"] = new SelectList(_context.Ippodroms, "Id", "Address", competition.IppodromId);
            return View(competition);
        }

        // GET: Competitions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Competitions == null)
            {
                return NotFound();
            }

            var competition = await _context.Competitions
                .Include(c => c.Ippodrom)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (competition == null)
            {
                return NotFound();
            }

            return View(competition);
        }

        // POST: Competitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Competitions == null)
            {
                return Problem("Entity set 'ApplicationContext.Competitions'  is null.");
            }
            var competition = await _context.Competitions.FindAsync(id);
            if (competition != null)
            {
                _context.Competitions.Remove(competition);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompetitionExists(int id)
        {
          return (_context.Competitions?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/HorsesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace SkachkiWebApp.Controllers
{
    public class HorsesController : Controller
    {
        private readonly ApplicationContext _context;

        public HorsesController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Horses
        public async Task<IActionResult> Index()
        {
            var applicationContext = _context.Horses.Include(h => h.HorseOwner);
            return View(await applicationContext.ToListAsync());
        }

        // GET: Horses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Horses == null)
            {
                return NotFound();
            }

            var horseModel = await _context.Horses
                .Include(h => h.HorseOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (horseModel == null)
            {
                return NotFound();
            }

            return View(horseModel);
        }

        // GET: Horses/Create
        public IActionResult Create()
        {
            ViewBag.HorseOwners = new SelectList(_context.HorseOwners, "Id", "Name");
            ViewBag.Sex = new SelectList(new string[] { "Male", "Female" });
            return View();
        }

        // POST: Horses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nickname,Sex,DOB,HorseOwnerId")] HorseModel horseModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(horseModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorseOwnerId"] = new SelectList(_context.HorseOwners, "Id", "Name", horseModel.HorseOwnerId);
            return View(horseModel);
        }

        // GET: Horses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Horses == null)
            {
                return NotFound();
            }

            var horseModel = await _context.Horses.FindAsync(id);
            if (horseModel == null)
            {
                return NotFound();
            }
            ViewBag.HorseOwners = new SelectList(_context.HorseOwners, "Id", "Name", horseModel.HorseOwnerId);
            ViewBag.Sex = new SelectList(new string[] { "Male", "Female" });
            return View(horseModel);
        }

        // POST: Horses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nickname,Sex,DOB,HorseOwnerId")] HorseModel horseModel)
        {
            if (id != horseModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(horseModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HorseModelExists(horseModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["HorseOwnerId"] = new SelectList(_context.HorseOwners, "Id", "Id", horseModel.HorseOwnerId);
            return View(horseModel);
        }

        // GET: Horses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Horses == null)
            {
                return NotFound();
            }

            var horseModel = await _context.Horses
                .Include(h => h.HorseOwner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (horseModel == null)
            {
                return NotFound();
            }

            return View(horseModel);
        }

        // POST: Horses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Horses == null)
            {
                return Problem("Entity set 'ApplicationContext.Horses'  is null.");
            }
            var horseModel = await _context.Horses.FindAsync(id);
            if (horseModel != null)
            {
                _context.Horses.Remove(horseModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HorseModelExists(int id)
        {
          return (_context.Horses?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/JokeysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace SkachkiWebApp.Controllers
{
    public class JokeysController : Controller
    {
        private readonly ApplicationContext _context;

        public JokeysController(ApplicationContext context)
        {
            _context = context;
        }

        // GET: Jokeys
        public async Task<IActionResult> Index()
        {
              return _context.Jokeys != null ? 
                          View(await _context.Jokeys.ToListAsync()) :
                          Problem("Entity set 'ApplicationContext.Jokeys'  is null.");
        }

        // GET: Jokeys/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jokeys == null)
            {
                return NotFound();
            }

            var jokey = await _context.Jokeys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jokey == null)
            {
                return NotFound();
            }

            return View(jokey);
        }

        // GET: Jokeys/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jokeys/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DOB,Rating")] JokeyModel jokey)
        {
            if (ModelState.IsValid)
            {
                if (jokey.Rating == null) jokey.Rating = 0;
                _context.Add(jokey);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jokey);
        }

        // GET: Jokeys/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jokeys == null)
            {
                return NotFound();
            }

            var jokey = await _context.Jokeys.FindAsync(id);
            if (jokey == null)
            {
                return NotFound();
            }
            return View(jokey);
        }

        // POST: Jokeys/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DOB,Rating")] JokeyModel jokey)
        {
            if (id != jokey.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jokey);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JokeyExists(jokey.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jokey);
        }

        // GET: Jokeys/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Jokeys == null)
            {
                return NotFound();
            }

            var jokey = await _context.Jokeys
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jokey == null)
            {
                return NotFound();
            }

            return View(jokey);
        }

        // POST: Jokeys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Jokeys == null)
            {
                return Problem("Entity set 'ApplicationContext.Jokeys'  is null.");
            }
            var jokey = await _context.Jokeys.FindAsync(id);
            if (jokey != null)
            {
                _context.Jokeys.Remove(jokey);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JokeyExists(int id)
        {
          return (_context.Jokeys?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Areas/admin/Views/CompetitionTickets/Create.cshtml
@model CompetitionTicketModel

@{
    ViewData["Title"] = "Create";
}

<h1>Добавление записи</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompetitionId" class="control-label">Турнир</label>
                <select asp-for="CompetitionId" class ="form-control" asp-items="ViewBag.Competitions"></select>
            </div>
            <div class="form-group">
                <label asp-for="HorseId" class="control-label">Лошадь</label>
                <select asp-for="HorseId" class ="form-control" asp-items="ViewBag.Horses"></select>
            </div>
            <div class="form-group">
                <label asp-for="JokeyId" class="control-label">Жокей</label>
                <select asp-for="JokeyId" class ="form-control" asp-items="ViewBag.Jokeys"></select>
            </div>
            <div class="form-group">
                <label asp-for="Result" class="control-label">Результат</label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Обратно к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/admin/Views/CompetitionTickets/Delete.cshtml
@model CompetitionTicketModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Удалить</h1>

<h3>Вы уверены что хотите удалить запись?</h3>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            Название турнира
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Competition.Name)
        </dd>
        <dt class = "col-sm-2">
            Лошадь
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Horse.Nickname)
        </dd>
        <dt class = "col-sm-2">
            Жокей
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jokey.Name)
        </dd>
        <dt class = "col-sm-2">
            Результат
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TiketId" />
        <input type="hidden" asp-for="CompetitionId" />
        <input type="hidden" asp-for="HorseId" />
        <input type="hidden" asp-for="JokeyId" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Обратно к списку</a>
    </form>
</div>

Areas/admin/Views/CompetitionTickets/Details.cshtml
@model CompetitionTicketModel

@{
    ViewData["Title"] = "Details";
}

<h1>Подробнее</h1>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            Название турнира
        </dt>
        <dd class = "col-sm-10">
            
            <a asp-area="admin" asp-controller="Competitions" asp-action="Details" asp-route-id="@Model.CompetitionId">@Html.DisplayFor(model => model.Competition.Name)</a>
        </dd>
        <dt class = "col-sm-2">
            Лошадь
        </dt>
        <dd class = "col-sm-10">
            <a asp-area="admin" asp-controller="Horses" asp-action="Details" asp-route-id="@Model.HorseId">@Html.DisplayFor(model => model.Horse.Nickname)</a>
        </dd>
        <dt class = "col-sm-2">
            Жокей
        </dt>
        <dd class = "col-sm-10">
            <a asp-area="admin" asp-controller="Jokeys" asp-action="Details" asp-route-id="@Model.JokeyId">@Html.DisplayFor(model => model.Jokey.Name)</a>
        </dd>
        <dt class = "col-sm-2">
            Результат
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TiketId">Редактировать</a> |
    <a asp-action="Index">Обратно к списку</a>
</div>

Areas/admin/Views/CompetitionTickets/Edit.cshtml
@model CompetitionTicketModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактирование</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TiketId" />
            <input type="hidden" asp-for="CompetitionId" />
            <input type="hidden" asp-for="HorseId" />
            <input type="hidden" asp-for="JokeyId" />
            <div class="form-group">
                <label asp-for="Result" class="control-label">Результат</label>
                <input asp-for="Result" class="form-control" />
                <span asp-validation-for="Result" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Обратно к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/admin/Views/CompetitionTickets/Index.cshtml
@model IEnumerable<CompetitionTicketModel>

@{
    ViewData["Title"] = "Competition Tickets";
}

<h1>Участие в соревнованиях</h1>

<p>
    <a asp-action="Create">Добавить новую запись</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Уникальный номер
            </th>
            <th>
                Название турнира
            </th>
            <th>
                Лошадь
            </th>
            <th>
                Жокей
            </th>
            <th>
                Результат
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TiketId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Competition.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Horse.Nickname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jokey.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Result)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.TiketId">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.TiketId">Подробнее</a> |
                <a asp-action="Delete" asp-route-id="@item.TiketId">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>